### ISSUE TITLE
Publish a dotnet global tool for JitDasm

### ISSUE THREAD

**Issue by damageboy** [0xd4d/JitDasm#2]
Would you consider accepting a PR for turning JitDasm into a [dotnet global tool](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools) so that users could install it quickly and use it without the ceremonial build process?

I'd provide a PR that builds a nupkg that could then be uploaded either manually or with a script to nuget.org whenever you would want to provide an update...

**Comment by 0xd4d** [comment]
Yes, the PR would be accepted.
